[package]
name = "common_test_utils"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tiny_http = "0.12.0"
walkdir = "2.5.0"
