[package]
name = "common_macros"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full"] }

[lib]
proc-macro = true
