[package]
name = "common_macros"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = { version = "2.0.98", features = ["full"] }

[lib]
proc-macro = true
