[package]
name = "slipway_increment_component"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
wit-bindgen = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }

[lib]
crate-type = ["cdylib"]

[features]
increment-ten = []
