[package]
name = "slipway_host"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
fontique = "0.2.0"
slipway_engine = { path = "../slipway_engine", features = [] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
