[package]
name = "slipway"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
clap = { version = "4.3.22", features = ["derive"] }
slipway-lib = { path = "../slipway-lib", features = ["unstable-test-utils"] }
slipway-wasmtime = { path = "../slipway-wasmtime" }
serde = { workspace = true }
serde_json = { workspace = true }
termion = "4.0.0"
ctrlc = "3.4.2"
edit = "0.1.5"
thiserror = { workspace = true }
anyhow = { workspace = true }
semver = { workspace = true }
jtd = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3.18"
viuer = { version = "0.8.1", features = ["sixel"] }
base64 = "0.22.1"
image = "0.25.2"

[dev-dependencies]
common-test-utils = { path = "../common-test-utils" }
