[package]
name = "slipway"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.3.22", features = ["derive"] }
slipway-lib = { path = "../slipway-lib", features = ["unstable-test-utils"] }
serde = { workspace = true }
serde_json = { workspace = true }
petgraph = "0.6.4"
termion = "4.0.0"
ctrlc = "3.4.2"
edit = "0.1.5"
thiserror = { workspace = true }
semver = { workspace = true }
jtd = { workspace = true }
wasmtime = "21.0.1"
wasi-common = "21.0.1"
tracing = { workspace = true }
tracing-subscriber = "0.3.18"
