[package]
name = "slipway-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.3.22", features = ["derive"] }
slipway-lib = { path = "../slipway-lib" }
