[test-groups]
cli-serial-tests = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'package(slipway) and test(/slipway_cli_serve_/)'
test-group = 'cli-serial-tests'
# retries = { backoff = "fixed", count = 4, delay = "1s" }
