[workspace]
members = ["slipway-lib", "slipway-cli", "component-url-loader"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["James Thurley"]

[workspace.dependencies]
float-cmp = "0.9.0"
mockall = "0.11.3"
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.104"
thiserror = "1.0.44"
semver = { version = "1.0.18", features = ["serde"] }
jtd = "0.3.1"
tracing = "0.1"