[package]
name = "slipway-lib"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
async-executor = "1.5.1"
async-trait = "0.1.73"
futures-lite = "1.13.0"
futures-util = "0.3.28"
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.104"
thiserror = "1.0.44"
