[package]
name = "slipway-lib"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
async-executor = "1.5.1"
async-trait = "0.1.73"
futures-lite = "1.13.0"
futures-util = "0.3.28"
jsonpath-rust = "0.4.0"
jtd = "0.3.1"
once_cell = "1.18.0"
oneshot = { version = "0.1.5", features = ["async"] }
regex = "1.9.5"
semver = { version = "1.0.18", features = ["serde"] }
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.104"
serde_with = { version = "3.5.1", default-features = false, features = ["std"] }
thiserror = "1.0.44"
typed-arena = "2.0.2"
url = "2.4.1"
